GET http://localhost:4004/odata/v4/viservice

###Read service metadata
GET http://localhost:4004/odata/v4/viservice/$metadata

###Get ANPR records
GET http://localhost:4004/odata/v4/viservice/ANPRSet
